source("Settings.R")
source("Preprocess.R")
source("Simulation.R")
initDir = getwd()
## setwd("../../CPLEXInput_HapMap300k_AutoImmune_Traits")
## W = randomizePhenotypes("CPLEXInputUKBB_all_unrelated_Autoimmune_11_HapMap300_chr3_subset11b_281591_149.csv.gz", numRandomizations = 10)
## print("Binning completed!")
## setwd("../../")
## Z = prepAllTriage(extra = 49L)
Q = processAllSimFiles(goodDir = "../../TriageInputs")
setwd(initDir)